// Package models provides data structures for the goUserAPI service.
package models

// User represents a user in the system exactly as specified in PRD (AC: #1)
// Following naming conventions: PascalCase structs, camelCase JSON fields, snake_case database columns
// Using Unix timestamps as required by Architecture.md
type User struct {
	ID            string `json:"id" db:"id" validate:"required,uuid"`                                     // UUID generated by PostgreSQL
	FirstName     string `json:"first_name" db:"first_name" validate:"required,max=100"`                  // Max 100 characters
	LastName      string `json:"last_name" db:"last_name" validate:"required,max=100"`                    // Max 100 characters
	Age           int    `json:"age" db:"age" validate:"required,gte=1,lte=120"`                          // 1-120 years validation
	RecordingDate int64  `json:"recording_date" db:"recording_date" validate:"required"`                   // Unix timestamp
}

// UserReport represents a user report in the system
// Using Unix timestamps as required by Architecture.md
type UserReport struct {
	ID            string `json:"id"`             // Unique report identifier
	UserID        string `json:"user_id"`        // Reference to user
	RecordingDate int64  `json:"recording_date"` // Date of recording (Unix timestamp)
	CreatedAt     int64  `json:"created_at"`     // Report creation time (Unix timestamp)
	UpdatedAt     int64  `json:"updated_at"`     // Last update time (Unix timestamp)
}
